In [1]:
import torch
import numpy as np
import torchvision
import math
import matplotlib.pyplot as plt

In [2]:
Input = torch.randn(1, 3, 32, 32)
Input.shape

torch.Size([1, 3, 32, 32])

### 1. MaxPool


In [3]:
maxpool2d=torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0,dilation=1, return_indices=False, ceil_mode=False)
torch_out=maxpool2d(Input)
torch_out

tensor([[[[ 1.2829,  1.2829, -0.1029,  ...,  0.8252,  0.9525,  0.9525],
          [ 1.1526,  1.7691,  1.7691,  ...,  0.8252,  0.9525,  0.9525],
          [ 0.8656,  1.7691,  1.7691,  ...,  0.9188,  0.5869,  0.3266],
          ...,
          [ 2.1082,  1.1558, -0.2775,  ...,  1.3607,  0.6565,  1.1572],
          [ 2.1082,  0.3891,  0.4362,  ...,  0.6565,  0.6565,  1.1913],
          [ 0.3891,  0.6254,  0.6254,  ..., -0.1341, -0.1341,  1.1913]],

         [[ 1.3563,  1.3563,  1.1360,  ...,  0.3573,  0.3573, -0.3561],
          [ 1.3563,  1.3563,  1.2140,  ...,  0.4801,  1.6927,  1.6927],
          [ 1.0673,  0.0790,  1.2140,  ...,  0.4801,  1.6927,  1.6927],
          ...,
          [ 1.3884,  0.6241,  0.6241,  ...,  0.8078,  0.4376,  0.4277],
          [ 0.8078,  0.6241,  0.6241,  ...,  0.8078,  0.1227,  0.6669],
          [-0.4200,  2.1429,  2.1429,  ...,  0.8518,  0.7344,  0.6669]],

         [[ 1.1043,  0.5253,  0.0627,  ...,  0.9127,  0.5070,  0.5070],
          [ 1.0315,  1.3407,  

In [4]:
def mymaxpool2d(Input, kernal_size, stride):
    batch,channel,height,width = Input.shape
    
    out_height = int((height-kernal_size)/stride)+1
    out_width = int ((width-kernal_size)/stride)+1
    print("out_shape", (out_height, out_width))
    out_pooling = torch.zeros((batch,channel, out_height, out_width))

    for img in range(batch):
        for map_num in range(channel):
            for h in range(out_height):
                for w in range(out_width):
                    out_pooling[img,map_num, h, w] = torch.max(Input[img,map_num, (h*stride):(h + kernal_size), (w*stride):(w + kernal_size)])
    return out_pooling


In [5]:
my_maxpool2d=mymaxpool2d(Input,2,1)
my_maxpool2d

out_shape (31, 31)


tensor([[[[ 1.2829,  1.2829, -0.1029,  ...,  0.8252,  0.9525,  0.9525],
          [ 1.1526,  1.7691,  1.7691,  ...,  0.8252,  0.9525,  0.9525],
          [ 0.8656,  1.7691,  1.7691,  ...,  0.9188,  0.5869,  0.3266],
          ...,
          [ 2.1082,  1.1558, -0.2775,  ...,  1.3607,  0.6565,  1.1572],
          [ 2.1082,  0.3891,  0.4362,  ...,  0.6565,  0.6565,  1.1913],
          [ 0.3891,  0.6254,  0.6254,  ..., -0.1341, -0.1341,  1.1913]],

         [[ 1.3563,  1.3563,  1.1360,  ...,  0.3573,  0.3573, -0.3561],
          [ 1.3563,  1.3563,  1.2140,  ...,  0.4801,  1.6927,  1.6927],
          [ 1.0673,  0.0790,  1.2140,  ...,  0.4801,  1.6927,  1.6927],
          ...,
          [ 1.3884,  0.6241,  0.6241,  ...,  0.8078,  0.4376,  0.4277],
          [ 0.8078,  0.6241,  0.6241,  ...,  0.8078,  0.1227,  0.6669],
          [-0.4200,  2.1429,  2.1429,  ...,  0.8518,  0.7344,  0.6669]],

         [[ 1.1043,  0.5253,  0.0627,  ...,  0.9127,  0.5070,  0.5070],
          [ 1.0315,  1.3407,  

### 2. AveragePool

In [6]:
avgpool2d=torch.nn.AvgPool2d(kernel_size=2, stride=1, padding=0,ceil_mode=False, count_include_pad=True,divisor_override=None)
torch_out=avgpool2d(Input)
torch_out


tensor([[[[ 0.2947, -0.0986, -0.4156,  ..., -0.3312,  0.2787, -0.1358],
          [ 0.2455,  0.4016,  0.5554,  ..., -0.1513,  0.6728, -0.0276],
          [ 0.1130,  0.4333,  0.4331,  ...,  0.2154, -0.1198, -0.2679],
          ...,
          [ 0.7697, -0.2363, -0.8697,  ..., -0.0617, -0.5585, -0.3400],
          [ 0.1650, -0.3609, -0.3534,  ..., -0.7970, -0.2486,  0.2079],
          [-0.4341,  0.0528, -0.2393,  ..., -0.4601, -0.4276, -0.3014]],

         [[ 0.6332,  0.9021,  0.0067,  ..., -0.2431, -0.2252, -0.6369],
          [ 0.4157,  0.1610,  0.4254,  ..., -0.4941,  0.3399,  0.2564],
          [-0.2757, -0.6481,  0.5986,  ..., -0.2630,  0.0407, -0.7226],
          ...,
          [ 0.3656, -0.2814, -0.0247,  ...,  0.0929, -0.4448, -0.3522],
          [-0.1879, -0.6623, -0.2619,  ...,  0.0045, -0.3366, -0.1055],
          [-0.9311, -0.6812, -0.1332,  ...,  0.4274,  0.2003,  0.2254]],

         [[ 0.0528, -1.0015, -0.8432,  ..., -0.3778, -0.2201, -0.0186],
          [-0.2226, -0.5585,  

In [7]:
def myavgpool2d(Input, kernal_size, stride):
    batch,channel,height,width = Input.shape
    
    out_height = int((height-kernal_size)/stride)+1
    out_width = int ((width-kernal_size)/stride)+1
    print("out_shape", (out_height, out_width))
    out_pooling = torch.zeros((batch,channel, out_height, out_width))

    for img in range(batch):
        for map_num in range(channel):
            for h in range(out_height):
                for w in range(out_width):
 
                        out_pooling[img,map_num, h, w] = Input[img,map_num, (h*stride):(h + kernal_size), (w*stride):(w + kernal_size)].mean()
    return out_pooling


In [8]:
my_avgpool2d=myavgpool2d(Input,2,1)
my_avgpool2d

out_shape (31, 31)


tensor([[[[ 0.2947, -0.0986, -0.4156,  ..., -0.3312,  0.2787, -0.1358],
          [ 0.2455,  0.4016,  0.5554,  ..., -0.1513,  0.6728, -0.0276],
          [ 0.1130,  0.4333,  0.4331,  ...,  0.2154, -0.1198, -0.2679],
          ...,
          [ 0.7697, -0.2363, -0.8697,  ..., -0.0617, -0.5585, -0.3400],
          [ 0.1650, -0.3609, -0.3534,  ..., -0.7970, -0.2486,  0.2079],
          [-0.4341,  0.0528, -0.2393,  ..., -0.4601, -0.4276, -0.3014]],

         [[ 0.6332,  0.9021,  0.0067,  ..., -0.2431, -0.2252, -0.6369],
          [ 0.4157,  0.1610,  0.4254,  ..., -0.4941,  0.3399,  0.2564],
          [-0.2757, -0.6481,  0.5986,  ..., -0.2630,  0.0407, -0.7226],
          ...,
          [ 0.3656, -0.2814, -0.0247,  ...,  0.0929, -0.4448, -0.3522],
          [-0.1879, -0.6623, -0.2619,  ...,  0.0045, -0.3366, -0.1055],
          [-0.9311, -0.6812, -0.1332,  ...,  0.4274,  0.2003,  0.2254]],

         [[ 0.0528, -1.0015, -0.8432,  ..., -0.3778, -0.2201, -0.0186],
          [-0.2226, -0.5585,  

### 3. Conv2d_1

In [10]:
Conv2d=torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=3, stride=1, padding=0, dilation=1,
                groups=1,bias=True, padding_mode='zeros')
torch_out=Conv2d(Input)
torch_out

tensor([[[[ 3.6010e-02,  4.6748e-01,  5.1160e-01,  ...,  7.7094e-01,
            4.2911e-03,  4.5387e-01],
          [ 1.0509e+00, -1.7034e-01,  3.3962e-01,  ...,  8.0045e-01,
           -4.3102e-01,  5.7322e-02],
          [-3.5085e-02, -6.1384e-01, -1.9673e-01,  ...,  1.1594e-01,
            5.7475e-01,  7.3934e-01],
          ...,
          [ 1.5204e-01, -5.6021e-01, -1.6509e-01,  ..., -7.7035e-02,
           -2.0199e-01,  1.5797e+00],
          [ 5.5852e-01, -7.7706e-01, -2.6420e-01,  ...,  6.3736e-01,
           -7.5282e-01,  1.1228e+00],
          [ 1.0545e+00, -1.2381e+00,  2.1575e-01,  ...,  1.0487e+00,
           -1.2557e+00,  2.2940e-01]],

         [[-3.3007e-01, -1.3424e-01, -9.4348e-01,  ..., -2.4776e-01,
            5.4668e-02, -2.7368e-01],
          [ 3.4796e-01,  1.1904e+00, -6.4207e-02,  ...,  1.0262e-01,
           -1.0418e+00, -4.6881e-01],
          [-4.2087e-01, -1.0154e+00,  8.5653e-01,  ..., -1.0917e+00,
            4.5367e-01,  2.9861e-01],
          ...,
     

In [11]:
conv_weight = Conv2d.weight.data
conv_bias = Conv2d.bias.data
conv_weight.shape

torch.Size([6, 3, 3, 3])

In [74]:
def myconv2d(Input, conv_weight, conv_bias, stride):
    batch,channel,height,width = Input.shape
    out_channel,_,k_h,k_w=conv_weight.shape
    
    out_height = int((height-k_h)/stride)+1
    out_width = int ((width-k_w)/stride)+1
    out_pooling = torch.zeros(batch,out_channel, out_height, out_width)

    for img in range(batch):
        for k in range(out_channel):
            for h in range(out_height):
                for w in range(out_width):
                    out_pooling[img,k, h, w] = torch.sum(Input[img,:, (h*stride):(h*stride + k_h), (w*stride):(w*stride +k_w )]
                                                                          *conv_weight[k,:,:,:])+conv_bias[k]
    return out_pooling
my_conv2d = myconv2d(Input, conv_weight, conv_bias, 1)
my_conv2d


tensor([[[[ 0.1752, -0.2181,  0.7335,  ...,  0.0169,  1.1395,  0.7046],
          [-0.4693, -0.0181, -1.2356,  ...,  1.2473, -0.6768, -0.1339],
          [ 0.6977,  0.3976,  0.4361,  ..., -0.4231, -0.6272, -0.3523],
          ...,
          [ 0.6289,  0.7697, -0.6303,  ..., -0.4405,  0.9620,  0.1331],
          [-0.4837, -0.3553,  0.2641,  ..., -0.3386,  0.5779,  0.5719],
          [-0.0796, -0.0370, -0.0980,  ...,  1.8525, -0.9600, -0.2636]],

         [[ 0.5579,  0.5961,  0.6262,  ...,  1.0438,  0.9116,  0.0307],
          [-0.3103, -0.1705, -0.1114,  ..., -0.0681,  0.1142,  0.2237],
          [ 0.3878,  0.0283,  0.5154,  ...,  0.4418,  0.2696,  0.0899],
          ...,
          [ 0.2792,  0.2168,  0.2422,  ...,  0.3149,  0.4593,  0.3218],
          [-0.1065, -0.3104,  0.3693,  ...,  0.5238, -0.3196, -0.8219],
          [-0.0605,  0.3406,  0.4682,  ..., -0.1180,  0.1329,  0.9546]],

         [[-1.0814, -0.1407,  0.3281,  ..., -0.2343,  0.1609, -0.0762],
          [ 1.0305,  1.2170,  

### 4. Conv2d_2 (stride=2,dilation=2)

In [15]:
Conv2d_2=torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=5, stride=2, padding=0, dilation=2, groups=1,
bias=True, padding_mode='zeros')
torch_out=Conv2d_2(Input)
torch_out

tensor([[[[-2.0293e-01, -1.0989e+00, -7.6421e-01, -5.7097e-02, -6.1847e-01,
           -3.2147e-01, -8.2310e-01, -1.5520e+00, -1.0093e+00, -2.2810e-01,
            9.2761e-02, -2.0570e-01],
          [ 8.1542e-01,  5.5698e-01,  2.8511e-01, -1.1589e+00, -1.0172e+00,
            5.4716e-01, -1.9442e-02,  4.4153e-01, -1.0483e+00,  1.1606e-01,
           -4.4759e-01, -8.8545e-02],
          [-4.4568e-01, -1.0027e+00,  2.7096e-01,  9.8192e-02, -3.0344e-01,
           -2.3090e-01, -6.0859e-01, -6.0224e-02, -7.3599e-01, -3.7175e-01,
            2.1801e-01, -1.7855e-01],
          [ 5.9326e-01, -3.0354e-01, -5.0270e-01, -4.0545e-01, -8.5303e-01,
           -3.8216e-01, -1.2511e+00, -3.6813e-01, -5.6396e-02,  8.6923e-01,
            1.1820e-01, -8.8790e-01],
          [-1.4698e+00, -3.3593e-01,  3.0265e-01,  1.8567e-02,  4.2161e-01,
           -1.3543e-01,  2.5053e-01, -2.1972e-02, -2.4065e-01, -6.9340e-01,
           -1.3648e-03, -8.7054e-01],
          [-3.5972e-01,  1.6425e-01, -3.6946e-01, 

In [12]:
conv_weight = Conv2d_2.weight.data
conv_bias = Conv2d_2.bias.data

NameError: name 'Conv2d_2' is not defined

In [13]:
def myconv2d_2(x, in_channels,out_channel,stride,bias,dilation):
    batch,channel,height,width = x.shape 
    
    k_h=conv_weight.shape[2]
    k_w=conv_weight.shape[3]
    
    dilation_k_h=k_h*dilation-1
    dilation_k_w =k_w*dilation-1
    
    out_height = int((height - dilation_k_h) / stride) + 1
    out_width = int((width - dilation_k_w) / stride) + 1
    out_pooling = torch.zeros(batch, out_channel, out_height, out_width)

    kernal = torch.zeros(out_channel, channel, dilation_k_h, dilation_k_w)

    for oc in range(out_channel):
        for c in range(channel):
            for kh in range(k_h):
                for kw in range(k_w):
                    kernal[oc, c, kh * dilation, kw * dilation] = conv_weight[oc, c, kh, kw]
    
    for img in range(batch):
        for oc in range(out_channel):
            for c in range(channel):
                for oh in range(out_height):
                    for ow in range(out_width):
                          out_pooling[img, oc, oh, ow] += (x[img, c, (oh * stride):(oh*stride + dilation_k_h), 
                                                 (ow * stride):(ow * stride + dilation_k_w)] * kernal[oc][c]).sum()
    
    for i in range(out_channel):
        out_pooling[0][i] += conv_bias[i]

    return out_pooling

myconv2D = myconv2d_2(Input,3, 6,2,  conv_bias,  2)

print(myconv2D)

tensor([[[[-0.3227,  1.0945, -0.4066,  ..., -0.0116,  0.5086, -0.3582],
          [-0.0304, -0.1673,  0.0192,  ...,  0.0505,  0.9767,  0.2686],
          [ 0.1303,  0.8969,  0.9048,  ...,  0.0638,  1.0998,  0.0781],
          ...,
          [ 0.0031, -0.0273, -0.1752,  ...,  1.3998, -1.1523, -0.0400],
          [ 0.0595, -0.5074, -0.0211,  ...,  0.8118,  0.2286, -0.6807],
          [ 1.0652, -0.1513, -0.5953,  ...,  0.0847,  0.5755, -0.1765]],

         [[-0.2350,  0.4856,  0.1485,  ..., -0.2693,  0.5169, -0.6167],
          [-1.0058, -0.5849, -1.3544,  ...,  0.3039, -0.5444,  0.7356],
          [ 0.4364,  0.4464, -0.7104,  ...,  0.8868,  0.1000,  0.3138],
          ...,
          [-0.8593,  0.1161, -1.4445,  ..., -0.0698, -0.6996,  1.0475],
          [ 0.6319,  0.3736, -0.1898,  ..., -0.6475, -0.5662,  0.8894],
          [-0.6387, -0.0723,  0.2246,  ..., -0.3117, -0.2371, -0.3065]],

         [[-0.3910,  0.4529,  1.1364,  ..., -0.1372, -0.5132,  0.5408],
          [ 0.6328,  0.8949, -

### 5. Transpose2d

In [14]:
transpose2d=torch.nn.ConvTranspose2d(in_channels=3, out_channels=4,kernel_size=3, stride=1, padding=0, output_padding=0,
groups=1, bias=True, dilation=1, padding_mode='zeros')
torch_out=transpose2d(Input)
torch_out


tensor([[[[-0.0863, -0.0959,  0.1366,  ...,  0.0448,  0.1552,  0.2327],
          [ 0.1668, -0.0056,  0.3439,  ..., -0.0769,  0.0692,  0.3117],
          [-0.0426, -0.0359, -0.6047,  ...,  0.6056, -0.2766,  0.3891],
          ...,
          [-0.0864, -0.7679,  0.9619,  ..., -0.0858,  0.0853, -0.2105],
          [ 0.0825, -0.0155, -0.4844,  ..., -0.3779, -0.0379, -0.1674],
          [ 0.0347,  0.2361,  0.4824,  ...,  0.5794, -0.1095,  0.1296]],

         [[-0.3260, -0.3619,  0.0392,  ..., -0.3219, -0.0880, -0.0659],
          [-0.1953,  0.0729,  0.4332,  ..., -0.2266,  0.2102, -0.0594],
          [-0.2894, -0.2544, -0.3938,  ...,  0.5970,  0.0449, -0.3454],
          ...,
          [-0.0495, -0.5375, -0.4395,  ..., -0.4690, -0.2876, -0.5074],
          [-0.2964,  0.0019, -0.2395,  ..., -0.4715,  0.1682, -0.4379],
          [-0.2731, -0.1913,  0.1112,  ...,  0.1555, -0.1470,  0.0475]],

         [[-0.0853, -0.1348,  0.4176,  ..., -0.1013, -0.0626, -0.1225],
          [-0.0089,  0.1148,  

In [15]:
conv_weight=transpose2d.weight.data
conv_bias=transpose2d.bias.data

In [16]:
def mytranspose2d(in_channel,out_channel,stride,bias,dilation, Input):

    batch,channel,height,width = Input.shape
    k_h=conv_weight.shape[2]
    k_w=conv_weight.shape[3]
    
    out_height = (height + k_h) - 1
    out_width = (width + k_w) - 1
    out_pooling = torch.zeros(batch, out_channel, out_height, out_width)
    
    for img in range(batch):
        for k in range(out_channel):
            for c in range(channel):
                for h in range(height):
                    for w in range(width):
                          out_pooling[img, k, h:h + k_h, w:w + k_w] += Input[img, c, h, w] * conv_weight[c][k]
    
    for i in range(out_channel):
        out_pooling[0][i] += conv_bias[i]

    return out_pooling

myconv2D = mytranspose2d(3, 4, 1,conv_bias, 1,Input)

print(myconv2D)

tensor([[[[-0.0863, -0.0959,  0.1366,  ...,  0.0448,  0.1552,  0.2327],
          [ 0.1668, -0.0056,  0.3439,  ..., -0.0769,  0.0692,  0.3117],
          [-0.0426, -0.0359, -0.6047,  ...,  0.6056, -0.2766,  0.3891],
          ...,
          [-0.0864, -0.7679,  0.9619,  ..., -0.0858,  0.0853, -0.2105],
          [ 0.0825, -0.0155, -0.4844,  ..., -0.3779, -0.0379, -0.1674],
          [ 0.0347,  0.2361,  0.4824,  ...,  0.5794, -0.1095,  0.1296]],

         [[-0.3260, -0.3619,  0.0392,  ..., -0.3219, -0.0880, -0.0659],
          [-0.1953,  0.0729,  0.4332,  ..., -0.2266,  0.2102, -0.0594],
          [-0.2894, -0.2544, -0.3938,  ...,  0.5970,  0.0449, -0.3454],
          ...,
          [-0.0495, -0.5375, -0.4395,  ..., -0.4690, -0.2876, -0.5074],
          [-0.2964,  0.0019, -0.2395,  ..., -0.4715,  0.1682, -0.4379],
          [-0.2731, -0.1913,  0.1112,  ...,  0.1555, -0.1470,  0.0475]],

         [[-0.0853, -0.1348,  0.4176,  ..., -0.1013, -0.0626, -0.1225],
          [-0.0089,  0.1148,  

### 6. Flatten

In [17]:
torch_out=torch.flatten(Input, start_dim=0, end_dim=-1)

torch_out

tensor([-0.5247,  1.2829, -0.8427,  ..., -1.3683,  1.8841, -0.4661])

In [18]:
def flatten(Input):
    return Input.reshape(-1)

flatten(Input)

tensor([-0.5247,  1.2829, -0.8427,  ..., -1.3683,  1.8841, -0.4661])

### 7. Sigmoid

In [19]:
torch_out=torch.sigmoid(Input,out=None)
torch_out

tensor([[[[0.3717, 0.7829, 0.3010,  ..., 0.3947, 0.4414, 0.4016],
          [0.7600, 0.3248, 0.4743,  ..., 0.6953, 0.7216, 0.2971],
          [0.4723, 0.6620, 0.8543,  ..., 0.6427, 0.5809, 0.3709],
          ...,
          [0.8917, 0.2017, 0.4311,  ..., 0.6585, 0.3319, 0.7608],
          [0.3867, 0.5961, 0.4553,  ..., 0.4665, 0.3063, 0.7670],
          [0.2611, 0.3489, 0.6514,  ..., 0.4553, 0.3590, 0.2690]],

         [[0.3716, 0.6442, 0.6278,  ..., 0.5884, 0.3906, 0.2889],
          [0.7518, 0.7952, 0.7569,  ..., 0.3877, 0.4119, 0.3003],
          [0.7441, 0.1337, 0.5052,  ..., 0.6178, 0.8446, 0.6307],
          ...,
          [0.6917, 0.3302, 0.6511,  ..., 0.2863, 0.4035, 0.3699],
          [0.3936, 0.3965, 0.1047,  ..., 0.5306, 0.4588, 0.6608],
          [0.3611, 0.0910, 0.8950,  ..., 0.6758, 0.5272, 0.5722]],

         [[0.7511, 0.6284, 0.1885,  ..., 0.1594, 0.6241, 0.3071],
          [0.4400, 0.2355, 0.1308,  ..., 0.5665, 0.5018, 0.5560],
          [0.7372, 0.3767, 0.7926,  ..., 0

In [20]:
def my_sigmoid(x):
    return 1 / (1+torch.exp(-x))

In [21]:
mysigmoid=my_sigmoid(Input)
mysigmoid

tensor([[[[0.3717, 0.7829, 0.3010,  ..., 0.3947, 0.4414, 0.4016],
          [0.7600, 0.3248, 0.4743,  ..., 0.6953, 0.7216, 0.2971],
          [0.4723, 0.6620, 0.8543,  ..., 0.6427, 0.5809, 0.3709],
          ...,
          [0.8917, 0.2017, 0.4311,  ..., 0.6585, 0.3319, 0.7608],
          [0.3867, 0.5961, 0.4553,  ..., 0.4665, 0.3063, 0.7670],
          [0.2611, 0.3489, 0.6514,  ..., 0.4553, 0.3590, 0.2690]],

         [[0.3716, 0.6442, 0.6278,  ..., 0.5884, 0.3906, 0.2889],
          [0.7518, 0.7952, 0.7569,  ..., 0.3877, 0.4119, 0.3003],
          [0.7441, 0.1337, 0.5052,  ..., 0.6178, 0.8446, 0.6307],
          ...,
          [0.6917, 0.3302, 0.6511,  ..., 0.2863, 0.4035, 0.3699],
          [0.3936, 0.3965, 0.1047,  ..., 0.5306, 0.4588, 0.6608],
          [0.3611, 0.0910, 0.8950,  ..., 0.6758, 0.5272, 0.5722]],

         [[0.7511, 0.6284, 0.1885,  ..., 0.1594, 0.6241, 0.3071],
          [0.4400, 0.2355, 0.1308,  ..., 0.5665, 0.5018, 0.5560],
          [0.7372, 0.3767, 0.7926,  ..., 0

### 8.roi Pool 

In [22]:
boxes = torch.Tensor([[0, 0, 0, 6.5, 6.5]])
torchvision.ops.roi_pool(Input,boxes,output_size=(3,3))

tensor([[[[1.7691, 1.7691, 1.3143],
          [1.7691, 2.4653, 0.9772],
          [0.7716, 1.6369, 1.6369]],

         [[1.3563, 1.7892, 1.7892],
          [1.9264, 1.7892, 1.7892],
          [1.2352, 1.7890, 1.6503]],

         [[1.3407, 1.3407, 1.3002],
          [1.9751, 1.9751, 2.4678],
          [1.4896, 1.4896, 1.4257]]]])

In [23]:

def my_roi_pool(Input, boxes, output_size):
    
    start_h = int(boxes[0][1])
    start_w = int(boxes[0][2])
    end_h = int(boxes[0][3]) 
    end_w = int(boxes[0][4])
    
    width = (end_w - start_w + 1)
    height = (end_h - start_h + 1)

    bin_w = width / output_size[0]
    bin_h = height / output_size[1]
    
    result = []
    for k in range(Input.shape[1]):
        temp = []
        for j in range(output_size[0]):
            sub_res = []
            for i in range(output_size[1]):
                sub_res.append(Input[..., int(0+bin_h*(j)):math.ceil(0+bin_h*(j+1)),
                                     int(0+bin_w*(i)):math.ceil(0+bin_w*(i+1))][0][k].max())
            temp.append(sub_res)
        result.append(temp)
    res=torch.Tensor(result)
    res = res.unsqueeze(0)
    return res

In [24]:
my_roi_pool(Input,boxes, (3,3))

tensor([[[[1.7691, 1.7691, 0.9772],
          [1.7691, 2.4653, 0.9772],
          [1.0588, 2.4653, 1.4429]],

         [[1.3563, 1.2140, 1.7892],
          [1.9264, 1.2140, 1.7892],
          [1.9264, 1.7890, 1.6556]],

         [[1.3407, 1.3407, 1.3002],
          [1.9751, 1.9751, 1.1975],
          [1.9751, 1.9751, 1.4257]]]])

### 9.batch_norm

In [25]:
channels = Input.shape[1]
mean = torch.Tensor([Input[0][i].mean() for i in range(Input.shape[1])])
var = torch.Tensor([Input[0][i].var() for i in range(Input.shape[1])])

In [26]:
torch.nn.functional.batch_norm(Input, running_mean=mean, running_var=var,weight=None, bias=None, training=False, momentum=0.1,eps=1e-05)


tensor([[[[-0.4961,  1.2706, -0.8068,  ..., -0.4010, -0.2133, -0.3731],
          [ 1.1433, -0.6984, -0.0838,  ...,  0.8233,  0.9477, -0.8248],
          [-0.0917,  0.6737,  1.7458,  ...,  0.5904,  0.3360, -0.4995],
          ...,
          [ 2.0772, -1.3280, -0.2544,  ...,  0.6584, -0.6668,  1.1477],
          [-0.4341,  0.3970, -0.1584,  ..., -0.1143, -0.7820,  1.1811],
          [-0.9998, -0.5930,  0.6280,  ..., -0.1582, -0.5498, -0.9603]],

         [[-0.5548,  0.5483,  0.4783,  ...,  0.3153, -0.4757, -0.9250],
          [ 1.0555,  1.3003,  1.0830,  ..., -0.4876, -0.3881, -0.8713],
          [ 1.0154, -1.8796, -0.0165,  ...,  0.4363,  1.6320,  0.4905],
          ...,
          [ 0.7595, -0.7345,  0.5783,  ..., -0.9374, -0.4225, -0.5624],
          [-0.4630, -0.4511, -2.1527,  ...,  0.0840, -0.1997,  0.6205],
          [-0.5997, -2.3067,  2.0758,  ...,  0.6871,  0.0705,  0.2496]],

         [[ 1.1226,  0.5314, -1.4954,  ..., -1.7023,  0.5128, -0.8360],
          [-0.2511, -1.2071, -

In [27]:
def batch_norm(Input,mean,var, momentum, eps):
    output = torch.zeros(Input.shape)
    for i in range(Input.shape[1]):
        output[0][i] = (Input[0][i] - mean[i])/(np.sqrt(var[i])-eps)
    return output
batch_norm(Input, mean, var,momentum=0.1, eps=1e-05)

tensor([[[[-0.4961,  1.2706, -0.8068,  ..., -0.4011, -0.2133, -0.3731],
          [ 1.1433, -0.6984, -0.0838,  ...,  0.8233,  0.9477, -0.8248],
          [-0.0917,  0.6737,  1.7458,  ...,  0.5904,  0.3360, -0.4995],
          ...,
          [ 2.0773, -1.3280, -0.2544,  ...,  0.6584, -0.6668,  1.1477],
          [-0.4341,  0.3970, -0.1584,  ..., -0.1143, -0.7820,  1.1811],
          [-0.9999, -0.5930,  0.6280,  ..., -0.1582, -0.5498, -0.9603]],

         [[-0.5548,  0.5484,  0.4783,  ...,  0.3153, -0.4757, -0.9250],
          [ 1.0555,  1.3003,  1.0831,  ..., -0.4876, -0.3881, -0.8713],
          [ 1.0154, -1.8797, -0.0165,  ...,  0.4363,  1.6320,  0.4905],
          ...,
          [ 0.7595, -0.7346,  0.5783,  ..., -0.9374, -0.4225, -0.5624],
          [-0.4630, -0.4511, -2.1527,  ...,  0.0840, -0.1997,  0.6206],
          [-0.5997, -2.3067,  2.0759,  ...,  0.6871,  0.0705,  0.2496]],

         [[ 1.1226,  0.5314, -1.4954,  ..., -1.7023,  0.5128, -0.8360],
          [-0.2511, -1.2071, -

### 10. Cross_entropy


In [28]:
target = torch.randint(3, (1,32,32))
Input = torch.randn(1, 3, 32, 32)
target

tensor([[[0, 1, 2,  ..., 0, 1, 1],
         [0, 2, 0,  ..., 2, 0, 1],
         [2, 1, 0,  ..., 2, 1, 2],
         ...,
         [2, 2, 0,  ..., 0, 2, 1],
         [2, 2, 0,  ..., 0, 1, 1],
         [1, 0, 0,  ..., 2, 2, 2]]])

In [29]:
torch_out= torch.nn.functional.cross_entropy(Input, target, weight=None,
size_average=None, ignore_index=-100, reduce=None,reduction='mean') 
torch_out

tensor(1.4000)

In [30]:
def softmax(x): 
    sof=torch.zeros(x.shape)
    for i in range (len(x)):
        loss=x[i].exp()/sum(x[i].exp())
        sof[i]=-torch.log(loss)
    return sof
        
def nl(input, target): 
    nloss = torch.zeros([len(input)])
    for i in range(len(input)):
        L=0
        for j in range(target[i].shape[1]):
            for k in range(target.shape[2]):
                L -= input[i,target[i,j,k],j,k]
        nloss[i]=- L/target.shape[1]/target.shape[2]
    return nloss
                
def cross_entropy(input,target):
    soft=softmax(input)
    loss=nl(soft,target)
    return loss

cross_entropy(Input,target)


tensor([1.4000])

### 11. Mse_loss

In [31]:
target = torch.randn(1,3,32,32)
torch.nn.functional.mse_loss(Input, target, size_average=None,
reduce=None, reduction='mean')

tensor(1.9923)

In [32]:
def mse(Input,target): 
    MSE = ((Input-target)**2).mean()
    return MSE

In [33]:
mse(Input,target)

tensor(1.9923)